title: "Application Onboarding (Licensed)"
path: /applications-onboard-licensed/
order: 9
section:
  - title: Network Edge Application Onboarding
    #path: /ido-specs/docs/applications-onboard/network-edge-applications-onboarding
    path: /ido-specs/docs/applications-onboard/network-edge-applications-onboarding
    meta_title: 
    meta_description: 
    
  - title: Edge DNS
    #path: /ido-specs/docs/applications-onboard/openness-edgedns
    path: /ido-specs/docs/applications-onboard/smartedge-open-edgedns
    meta_title: 
    meta_description: 
    
  - title: Edge Application Agent (EAA)
    #path: /ido-specs/docs/applications-onboard/openness-eaa
    path: /ido-specs/docs/applications-onboard/smartedge-open-eaa
    meta_title:
    meta_description: 
    
  - title: Certificate Signing
    #path: /ido-specs/docs/applications-onboard/openness-certsigner
    path: /ido-specs/docs/applications-onboard/smartedge-open-certsigner
    meta_title:
    meta_description:
    
  - title: Interface Service
    #path: /ido-specs/docs/applications-onboard/openness-interface-service
    path: /ido-specs/docs/applications-onboard/smartedge-open-interface-service
    meta_title:
    meta_description:
    
  - title: VM Support in IntelÂ® Smart Edge Open for Network Edge
    #path: /ido-specs/docs/applications-onboard/openness-network-edge-vm-support
    path: /ido-specs/docs/applications-onboard/smartedge-open-network-edge-vm-support
    meta_title: 
    meta_description: 
    
  - title: Core Network Configuration Agent  (CNCA)
    #path: /ido-specs/docs/applications-onboard/using-openness-cnca
    path: /ido-specs/docs/applications-onboard/using-smartedge-open-cnca
    meta_title: 
    meta_description: 